### PR TITLE
Add ini support

### LINKED ISSUE #52: Setup.cfg support?
Would you mind adding setup.cfg support for the configuration?

### PR DESCRIPTION
**Pull request by q0w**
# Description

Closes #52
# Before merge

- [ ] ``tox`` runs successfully
- [ ] Docs updated

# Before release (if applicable)

- [ ] Version updated in ``pyproject.toml``
- [ ] Version updated in pre-commit hook example
- [ ] Version updated in changelog
- [ ] Branch merged
- [ ] Tag created and pushed
- [ ] Published

### CODE REVIEW

**Comment by q0w** [comment]
> what if either files are unreadable or invalid?

Now if pyproject.toml file is invalid, it raises the error. If setup.cfg does not exist, it will ignore it and use `conf` from the previous step ( from_toml or EMPTY)

**Comment by ariebovenberg** [comment]
Thanks for getting this set up, very nice! 👍 

I can think of two next steps:
1. improve testing of `config.collect()`. I get the feeling the logic needs a tweak.
2. mention `setup.cfg` support in the docs

**Comment by ariebovenberg** [comment]
I you like I can take it from here and add the finishing touches. Let me know

**Comment by ariebovenberg** [comment]
Cool. Thanks for your contribution! 🏆

I'll be adding the finishing touches in the `next-release` branch, and merge this PR there.

**Pull request merged**
