### PR TITLE
Support packages that span multiple directories

### PR DESCRIPTION
**Pull request by eltoder**
I extracted this from #228 since it is unrelated to the rest of the changes.

### CODE REVIEW

**Comment by ariebovenberg** [comment]
@eltoder excellent work. After you rebase this branch, I can get to merging it.

**Comment by ariebovenberg** [comment]
let's see what the  'update branch' button does

...ah...a merge 😒

**Comment by ariebovenberg** [comment]
👀 did we just both rebase and force push? Anyways it looks like the commits are in order in the end 😄

**Review by ariebovenberg — APPROVED** [review]
Looks good 👍

**Comment by eltoder** [comment]
@ariebovenberg looks like we did :)

**Comment by ariebovenberg** [comment]
@eltoder any other related features you have planned? If not, I'll bundle your improvements into a new release

**Comment by eltoder** [comment]
@ariebovenberg That's it for now. Thank you for merging!

**Comment by ariebovenberg** [comment]
@eltoder thanks for your contribution 🤝

**Comment by ariebovenberg** [comment]
Release 0.19.0 is now out with the improved functionality 🚀

**Pull request merged**
